from flask import Blueprint, request, jsonify

from backend.database.connection import get_db_connection
from backend.services.deduplication import haversine_distance
from backend.services.prioritization import calculate_priority_score
from backend.config import Config
from authority.alert_service import get_all_alerts, update_alert_status


alerts_bp = Blueprint("alerts", __name__)


@alerts_bp.route("/api/alerts/proximity", methods=["GET"])
def get_proximity_alerts():
    try:
        user_lat = float(request.args.get("lat"))
        user_lng = float(request.args.get("lng"))
    except (TypeError, ValueError):
        return jsonify({
            "error": "Valid 'lat' and 'lng' query parameters required"
        }), 400

    alert_radius = Config.PROXIMITY_ALERT_RADIUS_METERS

    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM incidents WHERE status != 'RESOLVED'"
    )

    incidents = cursor.fetchall()
    conn.close()

    active_alerts = []

    for incident in incidents:
        dist = haversine_distance(
            user_lat,
            user_lng,
            incident["latitude"],
            incident["longitude"]
        )

        if dist <= alert_radius:
            score = calculate_priority_score(
                hazard_type=incident["hazard_type"],
                confidence=incident["confidence"],
                report_count=incident["report_count"]
            )

            if score >= 40.0:
                active_alerts.append({
                    "incident_id": incident["id"],
                    "hazard_type": incident["hazard_type"],
                    "distance_meters": round(dist, 1),
                    "priority_score": score,
                    "warning_level": (
                        "HIGH"
                        if score >= Config.HIGH_RISK_PRIORITY_SCORE
                        else "MEDIUM"
                    )
                })

    return jsonify({
        "alerts_count": len(active_alerts),
        "alerts": active_alerts
    }), 200


@alerts_bp.route("/api/alerts", methods=["GET"])
def get_authority_alerts():
    """
    Return authority alerts generated by Medha's
    Authority Action service.
    """
    alerts = get_all_alerts()

    return jsonify({
        "alerts_count": len(alerts),
        "alerts": alerts
    }), 200


@alerts_bp.route("/api/alerts/<alert_id>/status", methods=["PATCH"])
def change_authority_alert_status(alert_id):
    """
    Update the status of an authority alert.
    """
    data = request.get_json()

    if not data or "status" not in data:
        return jsonify({
            "error": "Status is required"
        }), 400

    try:
        alert = update_alert_status(
            alert_id,
            data["status"]
        )
    except ValueError as exc:
        return jsonify({
            "error": str(exc)
        }), 400

    if alert is None:
        return jsonify({
            "error": "Alert not found"
        }), 404

    return jsonify({
        "status": "SUCCESS",
        "alert": alert
    }), 200